name: insta_clone
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0


environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  cloud_firestore: ^4.5.2
  collection: ^1.17.0
  firebase_app_check: ^0.1.4+1
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  firebase_storage: ^11.1.1
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^5.0.8
  flutter_hooks: ^0.18.6
  font_awesome_flutter: ^10.4.0
  google_sign_in: ^6.1.0
  hooks_riverpod: ^2.3.5
  image: ^4.0.15
  image_picker: ^0.8.7+4
  intl: ^0.17.0
  lottie: ^2.3.2
  share_plus: ^6.3.2
  url_launcher: ^6.1.10
  uuid: ^3.0.7
  video_player: ^2.6.1
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/animations/
